<font color=#009afa size=50>DAT-6002 - Fundamentals of Artificial Intelligence</font><br>
<font size=50>WRIT1 Part 2 - Neural Networks</font><br>
<font size=20 color=#00c382>From Scratch MLP - Bank Data</font><br>

|**Assessment Code:** |WRIT1|
|---|---|
|**Author:**|Tom Rowan|
|**Course:**|DAT6002_S2_25|
|**Course Tutor:**|Imtiaz Hussain Khan, PhD|

**Coding Syntax Note: _variable_name --> temporary / locally used variable, discarded after use.**

https://archive.ics.uci.edu/dataset/222/bank+marketing

---

# Initialise Notebook

In [54]:
# Install Requirements Using Pip
%pip install -r requirements.txt

Requirement already satisfied: requests in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 1)) (2.32.5)
Requirement already satisfied: pandas in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: numpy in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 3)) (2.4.3)
Requirement already satisfied: matplotlib in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 4)) (3.10.8)
Requirement already satisfied: seaborn in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 5)) (0.13.2)
Requirement already satisfied: tabulate in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 6)) (0.10.0)
Requirement already satisfied: colorama in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 7)) (0.4.6)
Requirement already satisfied: cartopy in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 8)) (0.25.0)
Requirement already satisfied: geopandas in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 9)) (1.1.3)
Requirement already satisfied: pycountry in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 10)) (26.2.16)
Requirement already satisfied: scikit-learn in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 11)) (1.8.0)
Requirement already satisfied: plotly in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 12)) (6.6.0)
Requirement already satisfied: nbformat>=4.2.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 13)) (5.10.4)
Requirement already satisfied: notebook in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 14)) (7.5.5)
Requirement already satisfied: jupyterlab in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 15)) (4.5.6)
Requirement already satisfied: ipython in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 16)) (9.11.0)
Requirement already satisfied: geopy in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 17)) (2.4.1)
Requirement already satisfied: networkx in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 18)) (3.6.1)
Requirement already satisfied: pyvis in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from -r requirements.txt (line 19)) (0.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from requests->-r requirements.txt (line 1)) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from requests->-r requirements.txt (line 1)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from requests->-r requirements.txt (line 1)) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from requests->-r requirements.txt (line 1)) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from matplotlib->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from matplotlib->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from matplotlib->-r requirements.txt (line 4)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from matplotlib->-r requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from matplotlib->-r requirements.txt (line 4)) (26.0)
Requirement already satisfied: pillow>=8 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from matplotlib->-r requirements.txt (line 4)) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from matplotlib->-r requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: shapely>=2.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from cartopy->-r requirements.txt (line 8)) (2.1.2)
Requirement already satisfied: pyshp>=2.3 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from cartopy->-r requirements.txt (line 8)) (3.0.3)
Requirement already satisfied: pyproj>=3.3.1 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from cartopy->-r requirements.txt (line 8)) (3.7.2)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from geopandas->-r requirements.txt (line 9)) (0.12.1)
Requirement already satisfied: scipy>=1.10.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from scikit-learn->-r requirements.txt (line 11)) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from scikit-learn->-r requirements.txt (line 11)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from scikit-learn->-r requirements.txt (line 11)) (3.6.0)
Requirement already satisfied: narwhals>=1.15.1 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from plotly->-r requirements.txt (line 12)) (2.18.0)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from nbformat>=4.2.0->-r requirements.txt (line 13)) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from nbformat>=4.2.0->-r requirements.txt (line 13)) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from nbformat>=4.2.0->-r requirements.txt (line 13)) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from nbformat>=4.2.0->-r requirements.txt (line 13)) (5.14.3)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from notebook->-r requirements.txt (line 14)) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from notebook->-r requirements.txt (line 14)) (2.28.0)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from notebook->-r requirements.txt (line 14)) (0.2.4)
Requirement already satisfied: tornado>=6.2.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from notebook->-r requirements.txt (line 14)) (6.5.5)
Requirement already satisfied: async-lru>=1.0.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyterlab->-r requirements.txt (line 15)) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyterlab->-r requirements.txt (line 15)) (0.28.1)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyterlab->-r requirements.txt (line 15)) (7.2.0)
Requirement already satisfied: jinja2>=3.0.3 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyterlab->-r requirements.txt (line 15)) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyterlab->-r requirements.txt (line 15)) (2.3.0)
Requirement already satisfied: setuptools>=41.1.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyterlab->-r requirements.txt (line 15)) (82.0.1)
Requirement already satisfied: anyio in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from httpx<1,>=0.25.0->jupyterlab->-r requirements.txt (line 15)) (4.12.1)
Requirement already satisfied: httpcore==1.* in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from httpx<1,>=0.25.0->jupyterlab->-r requirements.txt (line 15)) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->-r requirements.txt (line 15)) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (25.1.0)
Requirement already satisfied: jupyter-client>=7.4.4 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (8.8.0)
Requirement already satisfied: jupyter-events>=0.11.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (0.5.4)
Requirement already satisfied: nbconvert>=6.4.4 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (7.17.0)
Requirement already satisfied: prometheus-client>=0.9 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (0.24.1)
Requirement already satisfied: pyzmq>=24 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (27.1.0)
Requirement already satisfied: send2trash>=1.8.2 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (1.9.0)
Requirement already satisfied: babel>=2.10 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.28.0->notebook->-r requirements.txt (line 14)) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.28.0->notebook->-r requirements.txt (line 14)) (0.13.0)
Requirement already satisfied: decorator>=5.1.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipython->-r requirements.txt (line 16)) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipython->-r requirements.txt (line 16)) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipython->-r requirements.txt (line 16)) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipython->-r requirements.txt (line 16)) (0.2.1)
Requirement already satisfied: pexpect>4.6 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipython->-r requirements.txt (line 16)) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipython->-r requirements.txt (line 16)) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipython->-r requirements.txt (line 16)) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipython->-r requirements.txt (line 16)) (0.6.3)
Requirement already satisfied: wcwidth in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->-r requirements.txt (line 16)) (0.6.0)
Requirement already satisfied: geographiclib<3,>=1.52 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from geopy->-r requirements.txt (line 17)) (2.1)
Requirement already satisfied: jsonpickle>=1.4.1 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from pyvis->-r requirements.txt (line 19)) (4.1.1)
Requirement already satisfied: argon2-cffi-bindings in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->-r requirements.txt (line 14)) (25.1.0)
Requirement already satisfied: appnope>=0.1.2 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab->-r requirements.txt (line 15)) (0.1.4)
Requirement already satisfied: comm>=0.1.1 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab->-r requirements.txt (line 15)) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab->-r requirements.txt (line 15)) (1.8.20)
Requirement already satisfied: nest-asyncio>=1.4 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab->-r requirements.txt (line 15)) (1.6.0)
Requirement already satisfied: psutil>=5.7 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab->-r requirements.txt (line 15)) (7.2.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jedi>=0.18.2->ipython->-r requirements.txt (line 16)) (0.8.6)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/tom/Documents/Data_Science/Year_3/cardiffmet-dat6002-artificial-intelligence/.venv/lib/python3.14/site-packages (from jinja2>=3.0.3->jupyterlab->-r requirements.txt (line 15)) (3.0.3)

### Import Python Libraries

In [55]:
# Standard Libraries
import sys
import time
import json
import random
from datetime import datetime

# Pandas and numpy
import pandas as pd
import numpy as np

# Matplot Lib
import matplotlib.pyplot as plt
from matplotlib import colormaps
import matplotlib.colors as mcolors
from matplotlib.pyplot import figure
import matplotlib.ticker as mticker
import matplotlib.animation as animation
%matplotlib inline

# Seaborn Graphs
import seaborn as sns

# Plotly
import plotly.express as px
import plotly.graph_objects as go

# Tabulate
from tabulate import tabulate

# Colorama
from colorama import Fore, Back, Style

# Requests
import requests

# Pycountry 
import pycountry

# GeoPy
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderServiceError

# Cartopy Maps
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# Geopandas
import geopandas as gpd

# IPython Display 
from IPython.display import HTML

# Do not print warnings!
import warnings
warnings.filterwarnings('ignore')

### Create a Timestamp

In [56]:
# Generate Timestamp
today = pd.Timestamp(datetime.today())
now_date_timestamp = str(today.strftime("%Y%m%d"))
now_datetime_timestamp = str(today.strftime("%Y%m%d-%H%M"))

### Functions for Pretty Output

print_output - Print coloured Output

In [57]:
# Function to print coloured output
def print_output (str1, str2, delim=':', colour='yellow'):
    if colour.upper() in dir(Fore):
        colour = colour.upper()
    else:
        colour = 'YELLOW'
    print (f'{getattr(Fore, colour)}{str(str1)}{delim}{Style.RESET_ALL} {str(str2)}')

### Check for Internet Access

In [58]:
_urls_to_check = ['http://connectivitycheck.gstatic.com/generate_204',
                  'https://www.github.com',
                  'https://datascience.daemonchild.com']

Set this to False if you have a local dataset

In [59]:
internet_required = False

In [60]:
# Function to Safely Check for Internet Connectivity
def check_internet (url_list):
    online = False
    for _url in url_list:
        try:
            response = requests.get(_url, timeout=3)
            if response.status_code == 200:
                online = True
                break
        except requests.RequestException:
            output_string = f"Check Internet failed for {_url}"
            print_output ('[FAIL]',output_string, colour='red', delim='')
    return online

# Perform the checks
if check_internet (_urls_to_check ):
    print_output ('[INTERNET]','Internet Connectivity Detected. Using Internet resources.',colour='green', delim='')
    online = True

else:
    print ()
    print_output ('[INTERNET]','No Internet Connectivity.', colour='red', delim='')
    online = False


# Stop running if Internet is required
if online == False & internet_required == True:
    sys.exit('Stopping notebook run here.')

[INTERNET] Internet Connectivity Detected. Using Internet resources.

---
# Load and Explore the Dataset

In [61]:
if online:
    # Fetch the dataset from the Internet
    df = pd.read_csv('bank-full.csv', delimiter=';')
else:
    # Load the dataset from local file
    df = pd.read_csv('bank-full.csv', delimiter=';')

### Explore the dataset

In [62]:
print (df.columns)
print ("")
print (df.shape)

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='str')

(45211, 17)

In [63]:
df.sample(10)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
22422,49,technician,married,secondary,no,1982,yes,yes,cellular,22,aug,73,15,-1,0,unknown,no
25154,48,management,married,tertiary,no,1600,no,no,cellular,18,nov,448,1,-1,0,unknown,no
42479,54,management,divorced,tertiary,no,380,no,yes,cellular,10,dec,501,1,188,2,success,no
27757,40,technician,single,secondary,no,2017,yes,no,cellular,28,jan,105,1,244,1,other,no
38508,42,entrepreneur,married,secondary,no,169,yes,no,telephone,15,may,87,4,-1,0,unknown,no
25318,30,management,married,secondary,no,1439,yes,no,cellular,18,nov,373,1,-1,0,unknown,no
6288,33,blue-collar,married,secondary,no,0,yes,no,unknown,27,may,190,1,-1,0,unknown,no
1926,41,services,married,secondary,no,510,yes,no,unknown,9,may,231,2,-1,0,unknown,no
15412,53,management,divorced,primary,no,-17,yes,yes,cellular,18,jul,508,1,-1,0,unknown,no
11909,46,management,married,secondary,no,12186,no,no,unknown,20,jun,29,3,-1,0,unknown,no

PCA... feature reduction... not for assessment, but read up.

In [64]:
df.dropna(inplace=True)
df.shape

(45211, 17)

# Conversion and Encoding Ready for the MLP

In [65]:
numerical_cols = df.select_dtypes(include=['number']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

# Binary columns that should not be one-hot encoded
binary_columns = ['default', 'housing', 'loan', 'y']

# Columns to exclude from the system
excluded_features = ['day', 'campaign', 'pdays', 'previous', 'y']

numerical_to_normalize = [col for col in numerical_cols if col not in binary_columns]
categorical_to_normalize = [col for col in categorical_cols if col not in binary_columns]

### Define Normalisation and Label Encoding Functions

$ X_scaled = \frac{max_X - min_X}{X-min_X}$

In [66]:
def max_min_normalize (df, column_name):
    max_value = df[column_name].max()
    min_value = df[column_name].min()
    df[column_name] = (df[column_name] - min_value) / (max_value - min_value)
    return df

def label_encode(df, column_name):
    # Get unique values in the column
    unique_values = df[column_name].unique()
    
    # Create a mapping of unique values to integers
    mapping = {value: i for i, value in enumerate(unique_values)}
    
    # Apply the mapping to the column
    df[column_name] = df[column_name].map(mapping).astype(float)
    return df

In [67]:
# Clean up the binary columns to be 0 and 1
for col in binary_columns:
    df[col] = df[col].map({'yes': 1.0, 'no': 0.0}).astype(float)

# Normalize the categorical columns using label encoding and then max-min normalization
for col in categorical_to_normalize:
    df = label_encode(df, col)
    df = max_min_normalize(df, col)

# Normalize the numerical columns using max-min normalization
for col in numerical_to_normalize:
    df = max_min_normalize(df, col)

In [68]:
df.sample(10)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
29895,0.181818,0.545455,0.5,0.333333,0.0,0.078959,1.0,0.0,0.5,0.100000,0.727273,0.321065,0.000000,0.283257,0.014545,0.333333,1.0
10922,0.311688,0.272727,0.0,0.666667,0.0,0.077561,0.0,0.0,0.0,0.533333,0.090909,0.044734,0.000000,0.000000,0.000000,0.000000,0.0
39172,0.142857,0.545455,0.5,0.333333,0.0,0.075582,1.0,0.0,0.5,0.566667,0.000000,0.157381,0.048387,0.000000,0.000000,0.000000,1.0
38358,0.350649,0.272727,0.0,1.000000,0.0,0.080974,1.0,0.0,1.0,0.466667,0.000000,0.005287,0.000000,0.391055,0.003636,0.333333,0.0
37282,0.181818,0.000000,0.5,0.333333,0.0,0.076580,1.0,0.0,0.5,0.400000,0.000000,0.058967,0.000000,0.202982,0.007273,0.333333,0.0
29632,0.207792,0.000000,0.0,0.000000,0.0,0.073702,0.0,1.0,0.5,0.066667,0.727273,0.053680,0.016129,0.000000,0.000000,0.000000,0.0
36387,0.168831,0.181818,0.0,0.000000,0.0,0.076662,1.0,0.0,0.5,0.333333,0.000000,0.019520,0.016129,0.000000,0.000000,0.000000,0.0
25028,0.363636,0.090909,0.5,0.333333,0.0,0.088764,1.0,0.0,0.5,0.566667,0.454545,0.022163,0.000000,0.000000,0.000000,0.000000,0.0
25425,0.428571,0.090909,0.0,0.333333,0.0,0.108202,1.0,1.0,1.0,0.566667,0.454545,0.016673,0.080645,0.000000,0.000000,0.000000,0.0
35047,0.441558,0.000000,0.5,0.000000,0.0,0.069771,1.0,0.0,0.5,0.166667,0.000000,0.081741,0.016129,0.000000,0.000000,0.000000,0.0

In [69]:
# sys.exit('Stopping notebook run here.')

---

### Write out the cleaned dataset for further use

In [70]:
# Create filenames, one timestamped, one 'latest'
filepath = "."
filename = f'{filepath}/bank_full_cleaned_{now_date_timestamp}.csv'
latest_filename = f'{filepath}/bank_full_cleaned_latest.csv'

# Write out CSV files
df.to_csv(filename, index=False)
df.to_csv(latest_filename, index=False)